### ISSUE TITLE
LED indicator bug

### ISSUE THREAD

**Issue by mxcdoam** [squee72564/F0_Minesweeper_Fap#5]
It seems like a bug in a LED indication: after a game is finished and exited led light stays on until another app use to it.
To reproduce:

Open minesweeper
Finish the game (win or loose). If won - blue led will light up. If lose - red led will up.
Exit the game. The led will stay on.
To turn off the led - open another app with led indication(I.e. NFC or RFID read functions will cause led blinking).

**Comment by squee72564** [comment]
Thanks for the feedback, I'll take a look and push a update soon.

**Comment by squee72564** [comment]
@mxcdoam So interestingly I am having trouble replicating the bug, which is strange because I felt like I noticed it once before you brought it to my attention. Are you using the most recent firmware update?

Anyways I added a call to reset the led before the app closes and frees all of its memory, and it seems like its working for me.

Would you be able to build the application from this repo via FBT or UFBT and test it on your end? The most recent update is on the main branch, and there is a general guide to using UFBT to build the app in the README if you haven't used it before.

**Comment by mxcdoam** [comment]
@squee72564 Yes, i was using the most recent firmware (really love this game so i was using it on at least 3 last FW versions). I've build and tested your update, seems like the issue is gone!
