### ISSUE TITLE
Ensure Solvable Setting doesn't save/persist

### ISSUE THREAD

**Issue by anthonydgallo** [squee72564/F0_Minesweeper_Fap#6]
I noticed that when I set Ensure Solvable to True and hit save - when I exit the app and return it still defaults to false.

This appears to be consistent every time.

**Comment by squee72564** [comment]
@anthonydgallo Hello, thanks for the comment. This is actually by design for a certain reason and I am open to suggestions on how to solve this design issue.

At the start of the game and when the game is reset the board is randomly set up with mines based on the difficulty level. The "Ensure Solvable" option will check the board layout to see if a basic algorithm can go through and solve the board without making any guesses.

One issue with the board verifying algorithm plus the random nature of the board generation is that if can take many tries of generating a random board and testing it before a valid unambiguous board is found. The board size, dimensions of the rows vs columns, and difficulty level all play a part into how fast the verifying algorithm can find a valid board; I haven't done extensive profiling but it can run through thousands and thousands of boards in the seconds it takes to generate and verify a valid map.

Sometimes the time it takes to generate a valid board is longer than a few seconds, and actually causes the UI to hang and freeze up for a little leading to an unpleasant user experience.

The reason I ultimately decided that "Ensure Solvable" setting would not persist in storage is because if it was enabled when the user first starts the game, and the board was a large board at max difficulty, the screen would appear to freeze up right after the splash screen for an indefinite time.

I figured for now until I figure out how to do the board generation and verification more gracefully, it was better to leave it initially disabled and allow the user to enable if needed.

Let me know if you have any other questions, and thanks for playing!

**Comment by anthonydgallo** [comment]
Hey @squee72564 makes total sense. Thanks for building this for Flipper. I have to admit I've passed countless hours over the last few weeks playing this 😂 great implementation for the flippers screen size.

**Comment by anthonydgallo** [comment]
Only suggestion I could add is maybe if you set a cap on the number of generations before falling back to "unsolvable". You mentioned potentially thousands of generations before finding one - maybe setting an iteration cap of 5,000 boards before falling back to the next generated board if a solvable one isn't found within the iteration limit. Whatever number makes sense - maybe 1-3 seconds with a view that says "generating solvable board" if they have the setting enabled.

**Comment by squee72564** [comment]
@anthonydgallo Yes I was thinking something along the same lines; maybe even allowing the user to press a button to stop the generation and continue.. I will need to restructure bits of the code reguardless so it will be some time down the line when I have a moment.
